services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    volumes:
      - database:/var/lib/mysql
    networks:
      - throttle
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "throttle"
      MYSQL_USER: "throttle"
      MYSQL_PASSWORD: "throttle"
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - throttle

  throttle:
    image: ghcr.io/srcdslab/throttle:0.0.1
    container_name: throttle
    restart: always
    depends_on:
      database:
        condition: service_healthy
    networks:
      - throttle
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./docker/php/php-fpm.conf:/etc/php/5.6/fpm/php-fpm.conf"
      - "./docker/app/config.php:/var/www/throttle/app/config.php"
      - "throttle-files:/var/www/throttle"

  webserver:
    image: nginx:stable-alpine
    container_name: webserver
    restart: always
    # ports:
    #   - "8001:80"
    depends_on:
      - database
      - throttle
    volumes:
      - "./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro"
      - "throttle-files:/var/www/throttle"
    networks:
      - proxy
      - throttle
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.$SERVICE_NAME-http.entrypoints=insecure
      - traefik.http.routers.$SERVICE_NAME-http.rule=Host(`throttle.example.com`)
      - traefik.http.routers.$SERVICE_NAME-https.entrypoints=secure
      - traefik.http.routers.$SERVICE_NAME-https.rule=Host(`throttle.example.com`)
      - traefik.http.services.$SERVICE_NAME.loadbalancer.server.port=80

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok
    restart: always
    ports:
      - "4040:4040"
    depends_on:
      - webserver
    volumes:
      - "./docker/ngrok/ngrok.yml:/etc/ngrok.yml"
    environment:
      NGROK_CONFIG: "/etc/ngrok.yml"
    profiles:
      - ngrok

volumes:
  database:
  throttle-files:

networks:
  throttle:
  proxy:
    external: true
